#!/bin/bash
docker run --rm -it \
	-v $PWD/src:/app/src \
	-v $PWD/testing:/app/testing \
	-v $PWD/package.json:/app/package.json \
	-v $PWD/../sv-graphql-client/src/:/app/node_modules/@simpleview/sv-graphql-client \
	-v /sv/applications/sv-auth/containers/graphql-v2/lib/test/auth_test.serviceAccount.json:/app/auth_test.serviceAccount.json \
	--add-host=graphql.kube.simpleview.io:192.168.50.100 \
	sv-auth-client:local /bin/bash